### ISSUE TITLE
Migration of project to bitcore

### ISSUE THREAD

**Issue by RdeWilde** [bitpay/bitcoind.js#62]
I read this project has been moved to bitcore. When I look at both sources they look very different.

How has the architecture/setup changed from one project to another? Any benefits for using this one over the newer one?

**Comment by carnesen** [comment]
@RdeWilde Like the readme says, this project is no longer actively maintained, and it hasn't been for a couple of years. I would advise against using this code for anything at this point. You might consider using the descendant of this project https://github.com/bitpay/bitcore-node. Careful there too though because it too appears to no longer be under active development (last commit was six months ago). Probably your best bet is to close this issue and seek assistance on whatever you're trying to achieve elsewhere.
